### ISSUE TITLE
error during make

### ISSUE THREAD

**Issue by june9713** [Terminus-IMRC/qpu-assembler2#17]
Hi, I Have one question.
I just download your project. flex is already installed.
So I type sudo make at the project folder and error is shown.

gcc    -o qasm2 rpn_calc.c.o diskstorage.c.o strtoint32_ex.c.o error_fl.c.o qasm2.c.o qasm2_anal.l.c.o
qasm2.c.o: In function `main':
/root/Downloads/videoCoreInC/qpu-assembler2/qasm2.c:16: undefined reference to `qasm2_assemble_file'
collect2: error: ld returned 1 exit status
Makefile:58: recipe for target 'qasm2' failed
make: *** [qasm2] Error 1

So I searched qasm2_assemble_file in qasm2.c but there is no function named "qasm2_assemble_file"
Could you let me know what was wrong please? :-)
Thanks!

**Comment by Terminus-IMRC** [comment]
Please run `make clean` and `make` again. I suspect you installed flex after the first build.

**Comment by june9713** [comment]
oh...yes! you are right! thanks!

**Comment by Terminus-IMRC** [comment]
I'm happy to hear that. I'll fix Makefile not to create empty file when lex is not found. Thank you for reporting!
